# ==============================================================================
# Workflow Name : Get Terraform
# File Name     : action.yaml
# Description   :
#   This composite GitHub Action installs Terraform CLI and gets Terraform output
#   from HashiCorp Cloud Platform (HCP) for a specified workspace. It also caches the
#   Terraform output to optimize subsequent runs.
#
# Author        : Vincent Huybrechts
# Created       : 2025-09-09
# Last Updated  : 2026-05-07
# Version       : 1.1.0
# ==============================================================================

name: Fetch Terraform Output
description: Restore Terraform output from cache or pull from HCP

inputs:
  WORKSPACE:
    description: Workspace
    required: true
  TFOUTPUT:
    description: Terraform output filename
    required: true
  TEMPPATH:
    description: Temporary path
    required: true
  APITOKEN:
    description: Terraform API Token
    required: true

runs:
  using: composite
  steps:
    # Set ENVIRONMENT path
    - name: Set ENVIRONMENT path
      shell: bash
      run: |
        mkdir -p ${{ inputs.TEMPPATH }}
        echo "TEMPPATH=${{ inputs.TEMPPATH }}" >> "$GITHUB_ENV"

    # Restore Terraform Cache
    - name: Restore Terraform Cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.TEMPPATH }}/${{ env.TFOUTPUT }}
        key: terraform-output-${{ inputs.WORKSPACE }}

    # Check for Restored Terraform Output
    - name: Check for Restored Terraform Output
      id: check-cache
      shell: bash
      run: |
        if [ -f "${TEMPPATH}/${{ env.TFOUTPUT }}" ]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi

    # Setup Terraform CLI
    - name: Setup Terraform CLI
      if: steps.check-cache.outputs.found == 'false'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.15.2

    # Download Terraform Output from HCP
    - name: Download Terraform Output from HCP
      if: steps.check-cache.outputs.found == 'false'
      shell: bash
      env:
        TF_TOKEN_app_terraform_io: ${{ inputs.APITOKEN }}
      run: |
        terraform login -no-color || true
        terraform pull -WORKSPACE="${{ inputs.WORKSPACE }}" > "${TEMPPATH}/tfstate.tfstate"
        terraform show -json "${TEMPPATH}/tfstate.tfstate" | jq '.values.outputs' > "${TEMPPATH}/${{ env.TFOUTPUT }}"

    # Debug output
    - name: View Debug Output
      shell: bash
      run: |
        jq '.' ${TEMPPATH}/${{ env.TFOUTPUT }} | head -n 20
