"""Cost estimation controller.

Orchestrates cost estimation for deployment builds using registered
cost estimator integrations (e.g. Infracost).

The controller is deliberately thin: it resolves the terraform build
artifacts from the work path, delegates to the ICostEstimator integration,
and returns structured results to the caller (CLI or programmatic use).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from strata.controllers.base_controller import BaseController
from strata.integrations.capabilities import ICostEstimator


class CostController(BaseController):
    """Controller for infrastructure cost estimation operations."""

    def __init__(self, work_path: Path) -> None:
        super().__init__()
        self._work_path = work_path

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def show(
        self,
        deployment_name: str,
        provisioner_name: str = "terraform",
        currency: Optional[str] = None,
    ) -> Tuple[bool, Dict[str, Any]]:
        """Get cost breakdown for a deployment's terraform artifacts.

        Reads terraform artifacts from the build directory, runs
        ``infracost breakdown``, and returns the parsed result.

        Args:
            deployment_name: Name of the deployment (used to locate build artifacts).
            provisioner_name: Provisioner directory under build artifacts (default: "terraform").
            currency: Optional ISO 4217 currency code (e.g. "EUR", "GBP").
                      Defaults to USD (Infracost default).

        Returns:
            Tuple of (success, result_dict).
            On success: result_dict contains the raw Infracost JSON output.
            On failure: result_dict contains ``{"error": "<reason>"}`` and
                        the error is also added to ``self._errors``.
        """
        estimator = self._get_estimator()
        if estimator is None:
            return self._fail("No cost estimator available. Install infracost: https://www.infracost.io/docs/install")

        available, msg = estimator.ensure_available()
        if not available:
            return self._fail(msg)

        terraform_path = self._resolve_terraform_path(deployment_name, provisioner_name)
        if terraform_path is None:
            return self._fail(
                f"No build artifacts found for '{deployment_name}'. Run: strata build run -f <deployment>"
            )

        if not (terraform_path / ".terraform").exists():
            return self._fail(f"Terraform not initialized at {terraform_path}. Run: terraform init")

        try:
            result = estimator.breakdown(str(terraform_path), currency=currency)
            self._add_message(f"Cost estimate retrieved for '{deployment_name}'")
            return True, result
        except Exception as exc:
            return self._fail(f"Cost estimation failed: {exc}")

    def diff(
        self,
        deployment_name: str,
        plan_file: str,
        provisioner_name: str = "terraform",
        currency: Optional[str] = None,
    ) -> Tuple[bool, Dict[str, Any]]:
        """Get cost diff between current state and a terraform plan.

        Intended for use during ``strata deploy --dry-run`` after
        ``terraform plan -out=plan.tfplan`` has been run.

        Args:
            deployment_name: Name of the deployment.
            plan_file: Path to the terraform plan JSON file
                       (generated by: terraform show -json plan.tfplan).
            provisioner_name: Provisioner directory under build artifacts (default: "terraform").
            currency: Optional ISO 4217 currency code.

        Returns:
            Tuple of (success, result_dict).
        """
        estimator = self._get_estimator()
        if estimator is None:
            return self._fail("No cost estimator available. Install infracost: https://www.infracost.io/docs/install")

        available, msg = estimator.ensure_available()
        if not available:
            return self._fail(msg)

        terraform_path = self._resolve_terraform_path(deployment_name, provisioner_name)
        if terraform_path is None:
            return self._fail(
                f"No build artifacts found for '{deployment_name}'. Run: strata build run -f <deployment>"
            )

        if not Path(plan_file).exists():
            return self._fail(f"Plan file not found: {plan_file}")

        try:
            result = estimator.diff(str(terraform_path), plan_file, currency=currency)
            self._add_message(f"Cost diff retrieved for '{deployment_name}'")
            return True, result
        except Exception as exc:
            return self._fail(f"Cost diff failed: {exc}")

    def is_available(self) -> bool:
        """Return True if a cost estimator integration is available and installed."""
        estimator = self._get_estimator()
        if estimator is None:
            return False
        available, _ = estimator.ensure_available()
        return available

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_estimator(self) -> Optional[ICostEstimator]:
        """Return the first available ICostEstimator integration, or None."""
        from strata.integrations.factory import IntegrationFactory

        for type_str in IntegrationFactory.get_known_types():
            try:
                integration = IntegrationFactory.create_by_type(type_str)
                if isinstance(integration, ICostEstimator):
                    return integration
            except Exception:
                continue
        return None

    def _resolve_terraform_path(
        self,
        deployment_name: str,
        provisioner_name: str = "terraform",
    ) -> Optional[Path]:
        """Find the terraform directory in build artifacts for a deployment.

        Searches: build/{deployment_name}*/terraform/{provisioner_name}/

        Args:
            deployment_name: Deployment name (matches directory prefix in build/).
            provisioner_name: Provisioner subdirectory name.

        Returns:
            Path to the terraform directory, or None if not found.
        """
        build_root = self._work_path / "build"
        if not build_root.exists():
            return None

        # Match build/{deployment_name} or build/{deployment_name}-{version}
        candidates: List[Path] = sorted(
            (d for d in build_root.iterdir() if d.is_dir() and d.name.startswith(deployment_name)),
            key=lambda p: p.stat().st_mtime,
            reverse=True,  # most recent first
        )

        for candidate in candidates:
            tf_path = candidate / "terraform" / provisioner_name
            if tf_path.exists():
                return tf_path

        return None

    def _fail(self, message: str) -> Tuple[bool, Dict[str, Any]]:
        """Add error and return a failure tuple."""
        self._add_error(message)
        return False, {"error": message}
