apiVersion: strata.huybrechts.xyz/v2
kind: providerconfig
meta:
  name: azure
spec:
  description: "Microsoft Azure provider type registry"
  version: "~>3.0"
  additional_regions: false
  regions:
    - name: westeurope
      geography: europe
      description: "West Europe (Netherlands)"
    - name: northeurope
      geography: europe
      description: "North Europe (Ireland)"
  additional_resources: false
  resources:
    - name: storage_account
      category: storage
      subcategory: blob
      description: "Azure Storage Account"
      additional_configurations: false
      configuration:
        account_tier: "^(Standard|Premium)$"
    - name: virtual_machine
      category: compute
      subcategory: virtualmachine
      description: "Azure Virtual Machine"
      additional_configurations: true
