# =============================================================================
# XYZ Platform - Terraform IaC Entry Point
# =============================================================================
# Variables are provided via tfvars files generated by the platform during
# deployment. Backend config is provided via backends/{env}.tfbackend.
#
# Usage:
#   terraform init -backend-config=backends/dev.tfbackend
#   terraform apply -var-file=dev.tfvars.json
# =============================================================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }

  backend "local" {
    # Override with -backend-config=backends/{env}.tfbackend
  }
}

# =============================================================================
# Resources
# =============================================================================

resource "null_resource" "deployment" {
  triggers = {
    deployment_id = local.deployment_id
    timestamp     = timestamp()
  }

  provisioner "local-exec" {
    command = "echo 'Deploying ${var.deployment_name} v${var.workspace_version} to ${var.environment}'"
  }
}
