# ============================================================================= 
# XYZ Platform - Terraform Infrastructure as Code
# ============================================================================= 
# This is the main entry point for the XYZ platform infrastructure.
# Variables are provided via tfvars files generated by the platform builder.
# =============================================================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
}

# =============================================================================
# Variables
# =============================================================================

# Workspace variables
variable "workspace_name" {
  description = "Name of the workspace"
  type        = string
}

variable "workspace_version" {
  description = "Version of the workspace"
  type        = string
}

variable "deployment_name" {
  description = "Name of the deployment"
  type        = string
}

variable "environment" {
  description = "Environment name (production, staging, development)"
  type        = string
}

variable "platform_version" {
  description = "Platform version"
  type        = string
}

variable "labels" {
  description = "Workspace labels"
  type        = map(string)
  default     = {}
}

variable "metadata" {
  description = "Additional workspace metadata"
  type        = any
  default     = {}
}

# Provider variables
variable "platform_providers" {
  description = "Provider configurations"
  type        = map(any)
  default     = {}
}

# Topology variables
variable "topologies" {
  description = "Topology configurations"
  type        = map(any)
  default     = {}
}

# Resource variables (dynamic by type)
variable "resources" {
  description = "Resource configurations"
  type        = map(any)
  default     = {}
}

# Module variables
variable "modules" {
  description = "Module configurations"
  type        = map(any)
  default     = {}
}

# =============================================================================
# Local Values
# =============================================================================

locals {
  # Common tags applied to all resources
  common_tags = merge(
    var.labels,
    {
      workspace   = var.workspace_name
      deployment  = var.deployment_name
      environment = var.environment
      managed_by  = "terraform"
      platform    = "xyz-platform"
    }
  )

  # Deployment identifier
  deployment_id = "${var.workspace_name}-${var.environment}"
}

# =============================================================================
# Test Resource (Placeholder)
# =============================================================================
# This is a placeholder resource to verify terraform execution.
# Replace with actual infrastructure resources.

resource "null_resource" "deployment" {
  triggers = {
    deployment_id = local.deployment_id
    timestamp     = timestamp()
  }

  provisioner "local-exec" {
    command = "echo 'Deploying ${var.deployment_name} v${var.workspace_version} to ${var.environment}'"
  }
}

# =============================================================================
# Outputs
# =============================================================================

output "deployment_info" {
  description = "Deployment information"
  value = {
    workspace_name    = var.workspace_name
    workspace_version = var.workspace_version
    deployment_name   = var.deployment_name
    environment       = var.environment
    platform_version  = var.platform_version
    deployment_id     = local.deployment_id
  }
}

output "providers" {
  description = "Configured providers"
  value       = var.platform_providers
  sensitive   = false
}

output "topologies" {
  description = "Infrastructure topologies"
  value       = var.topologies
  sensitive   = false
}

output "resource_count" {
  description = "Number of resources configured"
  value       = length(var.resources)
}

output "deployment_status" {
  description = "Deployment status message"
  value       = "XYZ Platform deployment '${var.deployment_name}' initialized successfully"
}
