apiVersion: strata.huybrechts.xyz/v1
kind: namespace
meta:
  name: xyz_base
  annotations:
    description: Base infrastructure stack for XYZ Platform
  labels:
    version: 1.0.0
  tags: [xyz,namespace]
spec:
  modules:
    - name: traefik
      file: "@xyz_configuration/stack/xyz-md-traefik.yaml"
