apiVersion: strata.huybrechts.xyz/v1
kind: provider
meta:
  name: xyz_dc_eu_fr
  annotations:
    description: Kamatera cloudprovider
  labels:
    version: "1.0.0"
  tags: [xyz,cloudprovider]
spec:
  properties:
    type: kamatera
    region: eu-fr
