apiVersion: strata.huybrechts.xyz/v1
kind: workspace
meta:
  name: xyz_platform
  annotations:
    description: Platform Workspace on Kamatera
  labels:
    version: "1.0.0"
  tags: [xyz, platform]
spec:
  providers:
    - name: kamatera_eu_fr
      file: "@xyz_configuration/stack/xyz-dc-eu-fr.yaml"

  provisioners:
    - name: xyz_iac
      provisioner: terraform
      source:
        repository: xyz_infrastructure
        source_path: terraform

  topology:
    - name: xzy_swarm
      provider: kamatera_eu_fr
      provisioner: xyz_iac
      type: docker_swarm
      volumes:
        - name: config
          type: replicated
        - name: docs
          type: replicated
        - name: data
          type: local
        - name: logs
          type: local
        - name: serve
          type: distributed
      components:
        # All component details are defined in resources section
        - resource: xyz_vm_manager
        - resource: xyz_vm_infra
        - resource: xyz_vm_worker

  resources:
    - name: xyz_vm_manager
      file: "@xyz_configuration/stack/xyz-rx-vm-manager.yaml"
      role: manager
      count: 1
      firewalls:
        - xyz_fw
    - name: xyz_vm_infra
      file: "@xyz_configuration/stack/xyz-rx-vm-infra.yaml"
      role: worker
      count: 2
      firewalls:
        - xyz_fw
    - name: xyz_vm_worker
      file: "@xyz_configuration/stack/xyz-rx-vm-worker.yaml"
      role: worker
      count: 2
      firewalls:
        - xyz_fw

  namespaces:
    - name: xyz_base
      file: "@xyz_configuration/stack/xyz-ns-base.yaml"

  firewalls:
    - name: xyz_fw
      file: "@xyz_configuration/stack/xyz-fw-base.yaml"
