#!/usr/bin/env python3
"""Built-in policy: enforce a maximum monthly cost threshold.

Evaluates at the ``plan`` phase. Reads ``cost.json`` from the build directory
(generated by ``strata cost show``) and compares the total monthly cost against
a configured maximum.

Graceful degradation
--------------------
- ``cost.json`` not found → skip (pass). Run ``strata cost show`` first.
- ``max_monthly`` not configured → skip (pass).
- Cost data is zero or unparseable → skip (pass with warning).
- ``environment_pattern`` configured → only evaluate for matching environment names.

Example configuration YAML::

    policies:
      - name: prod_cost_gate
        type: cost_threshold
        phase: plan
        enforcement: deny
        description: "Block deployments over €10,000/month"
        configuration:
          max_monthly: 10000
          currency: EUR              # informational only (not enforced)

      - name: dev_cost_cap
        type: cost_threshold
        phase: plan
        enforcement: warn
        description: "Warn when dev exceeds €500/month"
        configuration:
          max_monthly: 500
          environment_pattern: "dev*"
"""

import fnmatch
from typing import Any, Dict, Optional

from strata.logger import get_logger
from strata.models.policy_model import PolicyModel
from strata.validators.policies.base_policy import BasePolicy, PolicyContext, PolicyResult


class CostThresholdPolicy(BasePolicy):
    """Deny (or warn/audit) deployments whose estimated monthly cost exceeds the threshold."""

    def __init__(self, policy_model: PolicyModel) -> None:
        super().__init__(policy_model)
        self.logger = get_logger(__name__)

    def evaluate(self, context: PolicyContext) -> PolicyResult:
        configuration: Dict[str, Any] = self.policy.configuration or {}
        max_monthly: Optional[float] = configuration.get("max_monthly")
        currency: str = configuration.get("currency", "USD")
        env_pattern: Optional[str] = configuration.get("environment_pattern")

        # --- skip if not configured ---
        if max_monthly is None:
            return self._skip("max_monthly not configured")

        try:
            max_monthly = float(max_monthly)
        except (ValueError, TypeError):
            return self._skip("max_monthly is not a valid number")

        # --- skip if environment_pattern doesn't match ---
        if env_pattern:
            env_name = self._get_environment_name(context)
            if env_name and not fnmatch.fnmatchcase(env_name, env_pattern):
                return self._skip(f"environment '{env_name}' does not match pattern '{env_pattern}'")

        # --- skip if no cost data available ---
        if context.cost_data is None:
            return self._skip("cost.json not found — run 'strata cost show' before deploying")

        # --- resolve total monthly cost from cost.json ---
        total = self._extract_total_monthly(context.cost_data)
        if total is None:
            return self._skip("cost.json contains no parseable cost data")

        if total == 0.0:
            return self._skip("cost.json total is zero — skipping threshold check")

        # --- evaluate threshold ---
        passed = total <= max_monthly
        violations = []
        if not passed:
            violations.append(
                f"Estimated monthly cost {total:.2f} {currency} exceeds maximum {max_monthly:.2f} {currency}"
            )

        return PolicyResult(
            passed=passed,
            policy_name=self.name,
            enforcement=self.enforcement,
            policy_type="cost_threshold",
            violations=violations,
            details={
                "total_monthly": total,
                "max_monthly": max_monthly,
                "currency": currency,
            },
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _skip(self, reason: str) -> PolicyResult:
        self.logger.debug("cost_threshold_policy_skipped", policy=self.name, reason=reason)
        return PolicyResult(
            passed=True,
            policy_name=self.name,
            enforcement=self.enforcement,
            policy_type="cost_threshold",
            details={"skipped": reason},
        )

    def _get_environment_name(self, context: PolicyContext) -> Optional[str]:
        """Return the environment name from the deployment service, or None."""
        try:
            if context.deployment_service is None:
                return None
            env_service = context.deployment_service.get_environment_service()
            if env_service is None:
                return None
            return env_service.get_name()
        except Exception:
            return None

    def _extract_total_monthly(self, cost_data: Dict[str, Any]) -> Optional[float]:
        """Sum total monthly cost across all provisioners in cost.json.

        cost.json structure:
            {"provisioners": {"terraform": {"breakdown": {"totalMonthlyCost": "1202.40"}}}}

        Also handles top-level totalMonthlyCost for simpler structures.
        """
        total = 0.0
        found_any = False

        provisioners = cost_data.get("provisioners", {})
        if isinstance(provisioners, dict):
            for prov_data in provisioners.values():
                cost = self._extract_from_provisioner(prov_data)
                if cost is not None:
                    total += cost
                    found_any = True

        # Fallback: top-level totalMonthlyCost
        if not found_any:
            top_level = cost_data.get("totalMonthlyCost")
            if top_level is not None:
                try:
                    total = float(top_level)
                    found_any = True
                except (ValueError, TypeError):
                    pass

        return total if found_any else None

    def _extract_from_provisioner(self, prov_data: Any) -> Optional[float]:
        """Extract totalMonthlyCost from a single provisioner entry."""
        if not isinstance(prov_data, dict):
            return None

        # Try breakdown.totalMonthlyCost (Infracost v0.10 structure)
        breakdown = prov_data.get("breakdown")
        if isinstance(breakdown, dict):
            value = breakdown.get("totalMonthlyCost")
            if value is not None:
                try:
                    return float(value)
                except (ValueError, TypeError):
                    pass

        # Try projects[].breakdown.totalMonthlyCost (Infracost multi-project)
        projects = prov_data.get("projects")
        if isinstance(projects, list):
            total = 0.0
            for project in projects:
                proj_breakdown = project.get("breakdown", {}) if isinstance(project, dict) else {}
                value = proj_breakdown.get("totalMonthlyCost")
                if value is not None:
                    try:
                        total += float(value)
                    except (ValueError, TypeError):
                        pass
            if total > 0:
                return total

        # Try top-level totalMonthlyCost in the provisioner entry
        value = prov_data.get("totalMonthlyCost")
        if value is not None:
            try:
                return float(value)
            except (ValueError, TypeError):
                pass

        return None
