#!/usr/bin/env python3
"""
===============================================================================
Script Name   : config.py
Author        : Vincent Huybrechts
Version       : 1.0.0
Python Version: 3.12+
Description   : All fixed configuration values for the xyz-platform package.
===============================================================================
"""

# Build directory structure

# Build directory of the workspace / deployment
DEFAULT_BUILD_PATH = "build/app"

# Fetched repositories (cloned or pulled from remote)
# These are the raw repositories as fetched from their sources
DEFAULT_OBJECT_PATH = "build/obj"

# Distribution artifacts
# Artifacts generated by the platform for deployment
DEFAULT_DIST_PATH = "build/dist"

# Workspace state management
DEFAULT_STATE_DIR = ".xyz-platform"  # Hidden state directory in workspace
DEFAULT_STATE_FILE = "state.json"  # State file name

# List of valid script file extensions
SCRIPT_EXTENSIONS = {".sh", ".bash", ".py", ".ps1"}
