"""Service for loading and validating promotion-record files."""

from typing import List, Optional, Tuple

from strata.models.promotion_record_model import PromotionRecordModel
from strata.services.base_service import BaseService


class PromotionRecordService(BaseService["PromotionRecordModel"]):
    """Service for handling ``kind: promotion-record`` files.

    These files are machine-generated by ``strata promote start`` and
    ``strata promote rollback``. They are self-contained audit artifacts —
    no cross-reference validation is required.
    """

    def __init__(self, path: Optional[str] = None, data: Optional[dict] = None):
        super().__init__(path=path, data=data)
        self.model = None

    def _get_model_class(self):
        return PromotionRecordModel

    def _validate_dynamic(
        self,
        configuration_model=None,
        work_path: Optional[str] = None,
    ) -> Tuple[bool, List[str]]:
        """Promotion-record files are self-contained — no cross-reference validation."""
        return True, []
