#!/usr/bin/env python3
"""Service for loading version files and applying version pins to the environment merge chain."""

import hashlib
import re
from pathlib import Path
from typing import TYPE_CHECKING, Dict, List, Optional

if TYPE_CHECKING:
    from strata.models.workspace_model import WorkspaceSpecModel

import yaml

from strata.exceptions import PlatformFileNotFoundError
from strata.logger import get_logger
from strata.models.common_models import PlatformKind
from strata.models.environment_model import (
    EnvironmentModel,
    EnvironmentModuleOverrideModel,
    EnvironmentOverridesModel,
    EnvironmentRemoteOverrideModel,
    EnvironmentServiceImageOverrideModel,
)
from strata.models.version_lock_model import VersionLockModel, VersionPinTargetType, VersionPinTrack
from strata.models.version_manifest_model import VersionManifestModel

if TYPE_CHECKING:
    from strata.models.deployment_model import DeploymentVersionRef

logger = get_logger(__name__)

# Flat pin representation: target_type → {name: resolved_version}
PinDict = Dict[VersionPinTargetType, Dict[str, str]]


class VersionService:
    """Utilities for loading version files and applying version pins to the environment merge chain.

    This service is stateless — all methods are class methods or static methods.

    Resolution order (last-wins within each target type):
        1. version-manifest entries (human/tool-edited)
        2. version-lock entries (machine-generated by ``strata promote start``)

    Floating pins (``track: latest``) are included in the resolved dict using their
    last ``resolved`` value if present.  If ``resolved`` is absent the floating pin
    is skipped (no version to apply).
    """

    @classmethod
    def load(cls, path: str) -> VersionLockModel | VersionManifestModel:
        """Load a single version file (version-lock or version-manifest).

        Args:
            path: Absolute or work-path-relative path to the YAML file.

        Returns:
            Parsed VersionLockModel or VersionManifestModel.

        Raises:
            PlatformFileNotFoundError: If the file does not exist.
            ValueError: If the file is not a recognised version kind.
        """
        file_path = Path(path)
        if not file_path.exists():
            raise PlatformFileNotFoundError(str(file_path))

        with file_path.open("r", encoding="utf-8") as f:
            raw = yaml.safe_load(f)

        if not isinstance(raw, dict):
            raise ValueError(f"Version file is not a YAML mapping: {path}")

        kind = raw.get("kind")
        if kind == PlatformKind.VERSION_LOCK:
            lock = VersionLockModel.model_validate(raw)
            if lock.is_pointer:
                # New-style pointer lock: follow spec.source relative to the lock file's directory
                source_path = file_path.parent / lock.spec.source
                source_path = source_path.resolve()
                if not source_path.exists():
                    raise PlatformFileNotFoundError(
                        f"Lock '{file_path.name}' points to '{lock.spec.source}' which does not exist "
                        f"(resolved to '{source_path}')."
                    )
                # Hash verification: if the lock recorded spec.hash, the pointed-to version
                # file must still carry the same hash (i.e. spec.hash on the version file).
                if lock.spec.hash:
                    with source_path.open("r", encoding="utf-8") as _vf:
                        vf_raw = yaml.safe_load(_vf)
                    actual_hash = (vf_raw or {}).get("spec", {}).get("hash") if isinstance(vf_raw, dict) else None
                    if actual_hash and actual_hash != lock.spec.hash:
                        raise ValueError(
                            f"Lock '{file_path.name}' hash mismatch \u2014 "
                            f"version file '{lock.spec.source}' may have been modified since promotion. "
                            f"Expected: {lock.spec.hash[:20]}\u2026  Got: {actual_hash[:20]}\u2026"
                        )
                return cls.load(str(source_path))
            return lock
        elif kind == PlatformKind.VERSION_MANIFEST:
            return VersionManifestModel.model_validate(raw)
        else:
            raise ValueError(
                f"Unsupported kind '{kind}' in {path}. "
                f"Expected '{PlatformKind.VERSION_LOCK}' or '{PlatformKind.VERSION_MANIFEST}'."
            )

    @classmethod
    def resolve_pins(
        cls,
        models: List[VersionLockModel | VersionManifestModel],
    ) -> PinDict:
        """Flatten a list of version models into a per-type pin dict.

        Files are applied in list order — later entries win over earlier entries
        for the same target name and type.  This is the same last-wins semantics
        used by environment file merging.

        Floating pins (``track: latest``) contribute their ``resolved`` value when
        available; if ``resolved`` is absent the floating pin is skipped.

        Args:
            models: Ordered list of version models (manifest first, lock last is
                    the expected convention so the lock wins).

        Returns:
            Dict mapping VersionPinTargetType → {name: version_string}.
        """
        pins: PinDict = {
            VersionPinTargetType.REMOTE: {},
            VersionPinTargetType.HELM_CHART: {},
            VersionPinTargetType.IMAGE: {},
            VersionPinTargetType.TOOL: {},
        }

        for model in models:
            if isinstance(model, VersionLockModel):
                for pin in model.spec.pins:
                    if pin.track == VersionPinTrack.LATEST:
                        # Floating pin — use resolved value if present
                        version = pin.resolved
                        if version is None:
                            logger.debug(
                                "Skipping floating pin with no resolved value",
                                target=pin.target.name,
                                type=pin.target.type,
                            )
                            continue
                    else:
                        version = pin.version
                        if version is None:
                            logger.warning(
                                "Skipping pin with no version",
                                target=pin.target.name,
                                type=pin.target.type,
                            )
                            continue
                    pins[pin.target.type][pin.target.name] = version

            elif isinstance(model, VersionManifestModel):
                manifest_pins = model.spec.pins
                if manifest_pins.remotes:
                    for name, version in manifest_pins.remotes.items():
                        pins[VersionPinTargetType.REMOTE][name] = version
                if manifest_pins.charts:
                    for name, version in manifest_pins.charts.items():
                        pins[VersionPinTargetType.HELM_CHART][name] = version
                if manifest_pins.images:
                    for name, version in manifest_pins.images.items():
                        pins[VersionPinTargetType.IMAGE][name] = version
                if manifest_pins.tools:
                    for name, version in manifest_pins.tools.items():
                        pins[VersionPinTargetType.TOOL][name] = version

        return pins

    @classmethod
    def apply_to_environment(cls, env_model: EnvironmentModel, pins: PinDict) -> EnvironmentModel:
        """Apply resolved version pins to a merged EnvironmentModel.

        Pins are injected as additional overrides into the model's
        ``spec.overrides`` section using the same last-wins semantics as
        environment file merging.  Existing overrides for the same target are
        replaced; all other overrides are preserved.

        The input model is modified in place and also returned for chaining.

        Pin mapping:
            ``type: remote``     → ``spec.overrides.remotes`` (reference field)
            ``type: helm_chart`` → ``spec.overrides.modules`` (chart_version field)
            ``type: image``      → ``spec.overrides.modules`` (services[name].image field)

        For image pins the convention is that the pin ``name`` matches both the
        module name and the service name within that module.  This covers the
        common single-service-per-module pattern.  More complex cases (multiple
        services per module, or service name ≠ module name) can be handled in a
        future iteration.

        Args:
            env_model: Merged EnvironmentModel (from ``EnvironmentService.merge_envfiles``).
            pins: Flat pin dict from ``VersionService.resolve_pins``.

        Returns:
            The modified EnvironmentModel.
        """
        if not any(pins.values()):
            return env_model

        overrides = env_model.spec.overrides

        # Build mutable working copies of existing overrides
        remote_overrides: Dict[str, EnvironmentRemoteOverrideModel] = {}
        module_overrides: Dict[str, EnvironmentModuleOverrideModel] = {}

        if overrides:
            if overrides.remotes:
                for r in overrides.remotes:
                    remote_overrides[r.remote] = r
            if overrides.modules:
                for m in overrides.modules:
                    module_overrides[m.module] = m

        shadowed: List[str] = []

        # Apply remote pins
        for name, version in pins.get(VersionPinTargetType.REMOTE, {}).items():
            if name in remote_overrides:
                existing = remote_overrides[name].reference
                if existing != version:
                    shadowed.append(
                        f"Remote override '{name}' (reference={existing}) is shadowed "
                        f"by version pin reference={version}"
                    )
            remote_overrides[name] = EnvironmentRemoteOverrideModel(remote=name, reference=version)

        # Apply helm_chart pins
        for name, version in pins.get(VersionPinTargetType.HELM_CHART, {}).items():
            existing_mod = module_overrides.get(name)
            if existing_mod and existing_mod.chart_version and existing_mod.chart_version != version:
                shadowed.append(
                    f"Module override '{name}' (chart_version={existing_mod.chart_version}) "
                    f"is shadowed by version pin chart_version={version}"
                )
            if existing_mod:
                # Preserve other fields on the existing module override, only replace chart_version
                module_overrides[name] = existing_mod.model_copy(update={"chart_version": version})
            else:
                module_overrides[name] = EnvironmentModuleOverrideModel(module=name, chart_version=version)

        # Apply image pins
        for name, version in pins.get(VersionPinTargetType.IMAGE, {}).items():
            existing_mod = module_overrides.get(name)
            new_service_override = EnvironmentServiceImageOverrideModel(name=name, image=version)

            if existing_mod:
                # Merge service overrides: replace matching service by name, keep others
                existing_services = existing_mod.services or []
                merged_services = [s for s in existing_services if s.name != name]
                merged_services.append(new_service_override)
                module_overrides[name] = existing_mod.model_copy(update={"services": merged_services})
            else:
                module_overrides[name] = EnvironmentModuleOverrideModel(
                    module=name,
                    services=[new_service_override],
                )

        if shadowed:
            for msg in shadowed:
                logger.warning("Version pin shadows environment override — override has no effect", detail=msg)

        # Rebuild overrides with version pins applied
        existing_resources = overrides.resources if overrides else None
        existing_providers = overrides.providers if overrides else None
        existing_properties = overrides.properties if overrides else None
        existing_includes = overrides.includes if overrides else None
        existing_output_files = overrides.output_files if overrides else None

        new_overrides = EnvironmentOverridesModel(
            resources=existing_resources,
            modules=list(module_overrides.values()) or None,
            providers=existing_providers,
            remotes=list(remote_overrides.values()) or None,
            properties=existing_properties,
            includes=existing_includes,
            output_files=existing_output_files,
        )

        env_model.spec.overrides = new_overrides
        return env_model

    @classmethod
    def apply_to_workspace(cls, workspace_spec: "WorkspaceSpecModel", pins: PinDict) -> "WorkspaceSpecModel":
        """Apply resolved ``type: tool`` version pins to a WorkspaceSpecModel.

        Sets ``provisioner.version`` on each provisioner entry whose name matches a
        ``type: tool`` pin.  The input model is modified in place and returned for
        chaining.

        All other pin types are ignored — they target the environment model.

        Args:
            workspace_spec: Parsed WorkspaceSpecModel (from a WorkspaceService).
            pins: Flat pin dict from ``VersionService.resolve_pins``.

        Returns:
            The modified WorkspaceSpecModel.
        """
        tool_pins = pins.get(VersionPinTargetType.TOOL, {})
        if not tool_pins or not workspace_spec.provisioners:
            return workspace_spec

        for i, provisioner in enumerate(workspace_spec.provisioners):
            if provisioner.name in tool_pins:
                version = tool_pins[provisioner.name]
                workspace_spec.provisioners[i] = provisioner.model_copy(update={"version": version})
                logger.debug("Applied tool pin to provisioner", name=provisioner.name, version=version)

        return workspace_spec

    # Regexes for resolved_sha format validation (F-2)
    _GIT_SHA_RE = re.compile(r"^[0-9a-f]{7,40}$", re.IGNORECASE)
    _OCI_DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$", re.IGNORECASE)

    @classmethod
    def validate_sha_format(cls, target_type: VersionPinTargetType, sha: str) -> bool:
        """Return True when *sha* has a recognised immutable-reference format for *target_type*.

        Accepted formats:
            - ``remote``:                7–40 hex characters (git commit SHA / abbreviated SHA)
            - ``image`` / ``helm_chart``: ``sha256:<64 hex chars>`` (OCI content digest)
            - ``tool``:                   any non-empty string (no standard format)

        Args:
            target_type: The pin's target type.
            sha:         The ``resolved_sha`` value to validate.

        Returns:
            ``True`` if the format is recognised or the type has no strict format rule.
        """
        if target_type == VersionPinTargetType.REMOTE:
            return bool(cls._GIT_SHA_RE.match(sha))
        if target_type in (VersionPinTargetType.IMAGE, VersionPinTargetType.HELM_CHART):
            return bool(cls._OCI_DIGEST_RE.match(sha))
        # TOOL and any unknown types: any non-empty string is acceptable
        return bool(sha)

    @classmethod
    def find_shadowed_overrides(cls, env_model: EnvironmentModel, pins: PinDict) -> List[str]:
        """Return warning messages for any ``spec.overrides`` entries that are silently
        shadowed by ``pins`` (i.e., a version pin will overwrite the hand-written override).

        This is a **read-only** inspection — the model is not modified.  Suitable for
        use during ``strata validate --deep`` where env models must not be mutated.

        Returns:
            List of human-readable warning strings, one per shadowed override field.
            Empty list when no shadows are detected.
        """
        shadowed: List[str] = []
        overrides = env_model.spec.overrides if env_model.spec else None

        # Remote overrides shadowed by remote pins
        for name, version in pins.get(VersionPinTargetType.REMOTE, {}).items():
            if overrides and overrides.remotes:
                for r in overrides.remotes:
                    if r.remote == name and r.reference != version:
                        shadowed.append(
                            f"override for remote '{name}' (reference={r.reference!r}) is shadowed "
                            f"by versions pin reference={version!r} — the override has no effect"
                        )

        # Module chart_version overrides shadowed by helm_chart pins
        for name, version in pins.get(VersionPinTargetType.HELM_CHART, {}).items():
            if overrides and overrides.modules:
                for m in overrides.modules:
                    if m.module == name and m.chart_version and m.chart_version != version:
                        shadowed.append(
                            f"override for module '{name}' (chart_version={m.chart_version!r}) is shadowed "
                            f"by versions pin chart_version={version!r} — the override has no effect"
                        )

        return shadowed

    @classmethod
    def load_and_resolve(
        cls,
        version_refs: "List[DeploymentVersionRef]",
        objects_path: str,
        resolve_path_fn,
    ) -> PinDict:
        """Load all version files referenced in a deployment's ``spec.versions`` list
        and resolve them into a flat pin dict.

        Files are loaded in list order (manifest first, lock last is the expected
        convention). Missing files produce a warning and are skipped, not an error,
        so that deployments work before any lock file has been generated.

        Args:
            version_refs: List of ``DeploymentVersionRef`` entries from ``spec.versions``.
            objects_path: Base path for resolving relative file references.
            resolve_path_fn: Callable that resolves a file ref string (supports ``@repo/``
                             syntax) to an absolute path, same as used for environment files.

        Returns:
            Flat pin dict from ``VersionService.resolve_pins``.
        """
        models: List[VersionLockModel | VersionManifestModel] = []

        for ref in version_refs:
            try:
                abs_path = resolve_path_fn(ref.file, objects_path)
                model = cls.load(abs_path)
                models.append(model)
                logger.debug("Loaded version file", path=abs_path, kind=model.kind)
            except PlatformFileNotFoundError:
                logger.warning(
                    "Version file not found — skipping (no lock generated yet?)",
                    path=ref.file,
                )
            except Exception as e:
                logger.warning("Failed to load version file — skipping", path=ref.file, error=str(e))

        return cls.resolve_pins(models)
