{{- if .Values.db.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strata-server.fullname" . }}-db
  labels:
    {{- include "strata-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-url: {{ .Values.db.url | quote }}
{{- end }}
