{{- if .Values.adminToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strata-server.fullname" . }}-admin-token
  labels:
    {{- include "strata-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.adminToken | quote }}
{{- end }}
