apiVersion: v1
kind: Service
metadata:
  name: {{ include "strata-server.fullname" . }}
  labels:
    {{- include "strata-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "strata-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: 8443
