# =========================================================
# This file is auto-generated. Do not edit directly.
# Generated by tfgenvars.py script.
# For Workspace: platform
# =========================================================

# Variables need to be set
# tf_vars_kamatera_api_key
# tf_vars_kamatera_api_secret
# tf_vars_kamatera_public_key
# tf_vars_kamatera_root_password

# Kamatera Variables
kamatera_country    = "Germany"
kamatera_region     = "Frankfurt"
kamatera_manager_id = "manager-1"

# Server Variables
virtualmachines = {
  "vm-manager" = {
    provider  = "kamatera"
    role      = "manager"
    count     = 1
    os_name   = "Ubuntu"
    os_code   = "24.04 64bit"
    cpu_type  = "A"
    cpu_cores = 1
    ram_mb    = 1024
    disks_gb  = [20]
    billing   = "hourly"
    unit_cost = 5.0
  }
  "vm-infrastructure" = {
    provider  = "kamatera"
    role      = "infra"
    count     = 1
    os_name   = "Ubuntu"
    os_code   = "24.04 64bit"
    cpu_type  = "A"
    cpu_cores = 1
    ram_mb    = 4096
    disks_gb  = [20, 40]
    billing   = "hourly"
    unit_cost = 11.0
  }
  "vm-worker" = {
    provider  = "kamatera"
    role      = "worker"
    count     = 1
    os_name   = "Ubuntu"
    os_code   = "24.04 64bit"
    cpu_type  = "A"
    cpu_cores = 1
    ram_mb    = 2048
    disks_gb  = [20]
    billing   = "hourly"
    unit_cost = 6.0
  }
}
