apiVersion: strata.huybrechts.xyz/v1
kind: namespace
meta:
  name: ${solution_name}_ns_app
  annotations:
    description: Application namespace for ${solution_name} services
  labels:
    version: "1.0.0"
  tags: [${solution_name}, namespace, app]
spec:
  modules:
    - name: api
      file: "@${solution_name}/stack/mod-api.yaml"
